// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIXjgkTRirmEM8t3AHPBXjXFPTr8YX6sU',
    appId: '1:219368554304:web:9ba1d3c983d3706c0984a5',
    messagingSenderId: '219368554304',
    projectId: 'chat-f30cd',
    authDomain: 'chat-f30cd.firebaseapp.com',
    storageBucket: 'chat-f30cd.appspot.com',
    measurementId: 'G-Y1LTY7YPN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwD34dGx9QdKHoTqMsPppmkbf_ht34pog',
    appId: '1:219368554304:android:3c512a0c876249880984a5',
    messagingSenderId: '219368554304',
    projectId: 'chat-f30cd',
    storageBucket: 'chat-f30cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv7x2qmswTqXBxzqYLxGFlEi91qF35DIk',
    appId: '1:219368554304:ios:749e0dc519e2cfa30984a5',
    messagingSenderId: '219368554304',
    projectId: 'chat-f30cd',
    storageBucket: 'chat-f30cd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv7x2qmswTqXBxzqYLxGFlEi91qF35DIk',
    appId: '1:219368554304:ios:c56f5276e0fd34d50984a5',
    messagingSenderId: '219368554304',
    projectId: 'chat-f30cd',
    storageBucket: 'chat-f30cd.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
